### ISSUE TITLE
GPU Memory Loaded, but 0 Utilization

### ISSUE THREAD

**Issue by skyler1253** [ildoonet/tf-pose-estimation#406]
@ildoonet I am trying to restore mobilenet_thin weights and continue training on Ubuntu 16 + CUDA 9.0 + CUDNN 7.5 + Tensorflow-gpu 1.8 with a smaller subset of the coco training data as a proof of concept before I work in my own training data.  I'm using 8 NVIDIA Tesla K80 GPU's through Google Cloud.  

I can get the GPU's fully loaded with data (Batch size 96), but the model training isn't executing on the GPU - I see GPU utilization 0%.  I can validate that my GPU configuration works well with an MNIST pipeline and it seems to work just fine.  Any thoughts on why I can't seem to get the train steps to execute on a GPU? I stall out after "Training started" with CPU utilization 100%.

**Comment by skyler1253** [comment]
Looks like the issue was the CPU bottleneck mentioned in other places.  I had to change line 367 in the pose_dataset.py file:

ds = PrefetchData(ds, 1000, multiprocessing.cpu_count() * 4)

Something about multiplying by 4 was giving me issues.  As soon as I dropped the 4 I was all set.

**Comment by ildoonet** [comment]
try with the codes in brach 'dev/mobilenet-v2...

I improved preprocess parts so cpu utilizations are less than before.
